version: '3'

services:
  httpd:
    container_name: httpd-container
    build: ./httpd
    privileged: true
    ports:
      - "80:80"
  tomcat:
    container_name: tomcat-container
    build: ./tomcat
    # もしアプリを乗せたかったら
    #    volumes:
    #      - ./tomcat/webapps:/usr/local/tomcat/webapps
    expose:
      - "8009"
    environment:
      - 'CATALINA_OPTS=-Duser.timezone=Asia/Tokyo' # コンテナ内のtimezoneをJSTに変更